package org.openhmis.domain;

// Generated Jul 29, 2015 7:35:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchemaVersion generated by hbm2java
 */
@Entity
@Table(name = "schema_version", catalog = "openhmis")
public class SchemaVersion implements java.io.Serializable {

	private String version;
	private int versionRank;
	private int installedRank;
	private String description;
	private String type;
	private String script;
	private Integer checksum;
	private String installedBy;
	private Date installedOn;
	private int executionTime;
	private boolean success;

	public SchemaVersion() {
	}

	public SchemaVersion(String version, int versionRank, int installedRank,
			String description, String type, String script, String installedBy,
			Date installedOn, int executionTime, boolean success) {
		this.version = version;
		this.versionRank = versionRank;
		this.installedRank = installedRank;
		this.description = description;
		this.type = type;
		this.script = script;
		this.installedBy = installedBy;
		this.installedOn = installedOn;
		this.executionTime = executionTime;
		this.success = success;
	}

	public SchemaVersion(String version, int versionRank, int installedRank,
			String description, String type, String script, Integer checksum,
			String installedBy, Date installedOn, int executionTime,
			boolean success) {
		this.version = version;
		this.versionRank = versionRank;
		this.installedRank = installedRank;
		this.description = description;
		this.type = type;
		this.script = script;
		this.checksum = checksum;
		this.installedBy = installedBy;
		this.installedOn = installedOn;
		this.executionTime = executionTime;
		this.success = success;
	}

	@Id
	@Column(name = "version", unique = true, nullable = false, length = 50)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "version_rank", nullable = false)
	public int getVersionRank() {
		return this.versionRank;
	}

	public void setVersionRank(int versionRank) {
		this.versionRank = versionRank;
	}

	@Column(name = "installed_rank", nullable = false)
	public int getInstalledRank() {
		return this.installedRank;
	}

	public void setInstalledRank(int installedRank) {
		this.installedRank = installedRank;
	}

	@Column(name = "description", nullable = false, length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "script", nullable = false, length = 1000)
	public String getScript() {
		return this.script;
	}

	public void setScript(String script) {
		this.script = script;
	}

	@Column(name = "checksum")
	public Integer getChecksum() {
		return this.checksum;
	}

	public void setChecksum(Integer checksum) {
		this.checksum = checksum;
	}

	@Column(name = "installed_by", nullable = false, length = 100)
	public String getInstalledBy() {
		return this.installedBy;
	}

	public void setInstalledBy(String installedBy) {
		this.installedBy = installedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "installed_on", nullable = false, length = 19)
	public Date getInstalledOn() {
		return this.installedOn;
	}

	public void setInstalledOn(Date installedOn) {
		this.installedOn = installedOn;
	}

	@Column(name = "execution_time", nullable = false)
	public int getExecutionTime() {
		return this.executionTime;
	}

	public void setExecutionTime(int executionTime) {
		this.executionTime = executionTime;
	}

	@Column(name = "success", nullable = false)
	public boolean isSuccess() {
		return this.success;
	}

	public void setSuccess(boolean success) {
		this.success = success;
	}

}
