package org.openhmis.domain;

// Generated Aug 4, 2015 11:17:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProject generated by hbm2java
 */
@Entity
@Table(name = "TMP_PROJECT", catalog = "openhmis")
public class TmpProject implements java.io.Serializable {

	private Integer projectId;
	private String projectName;
	private Integer continuumProject;
	private Integer projectType;
	private Integer residentialAffiliation;
	private Integer resProjectId;
	private Integer trackingMethod;
	private Integer targetPopulation;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpProject() {
	}

	public TmpProject(String projectName, Integer continuumProject,
			Integer projectType, Integer residentialAffiliation,
			Integer resProjectId, Integer trackingMethod,
			Integer targetPopulation, Date dateCreated, Date dateUpdated) {
		this.projectName = projectName;
		this.continuumProject = continuumProject;
		this.projectType = projectType;
		this.residentialAffiliation = residentialAffiliation;
		this.resProjectId = resProjectId;
		this.trackingMethod = trackingMethod;
		this.targetPopulation = targetPopulation;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "projectId", unique = true, nullable = false)
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "projectName")
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "continuumProject")
	public Integer getContinuumProject() {
		return this.continuumProject;
	}

	public void setContinuumProject(Integer continuumProject) {
		this.continuumProject = continuumProject;
	}

	@Column(name = "projectType")
	public Integer getProjectType() {
		return this.projectType;
	}

	public void setProjectType(Integer projectType) {
		this.projectType = projectType;
	}

	@Column(name = "residentialAffiliation")
	public Integer getResidentialAffiliation() {
		return this.residentialAffiliation;
	}

	public void setResidentialAffiliation(Integer residentialAffiliation) {
		this.residentialAffiliation = residentialAffiliation;
	}

	@Column(name = "resProjectId")
	public Integer getResProjectId() {
		return this.resProjectId;
	}

	public void setResProjectId(Integer resProjectId) {
		this.resProjectId = resProjectId;
	}

	@Column(name = "trackingMethod")
	public Integer getTrackingMethod() {
		return this.trackingMethod;
	}

	public void setTrackingMethod(Integer trackingMethod) {
		this.trackingMethod = trackingMethod;
	}

	@Column(name = "targetPopulation")
	public Integer getTargetPopulation() {
		return this.targetPopulation;
	}

	public void setTargetPopulation(Integer targetPopulation) {
		this.targetPopulation = targetPopulation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
