package org.openhmis.domain;

// Generated Aug 4, 2015 11:17:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProjectContinuum generated by hbm2java
 */
@Entity
@Table(name = "TMP_PROJECT_CONTINUUM", catalog = "openhmis")
public class TmpProjectContinuum implements java.io.Serializable {

	private Integer projectCocId;
	private Integer projectId;
	private String cocCode;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpProjectContinuum() {
	}

	public TmpProjectContinuum(Integer projectId, String cocCode,
			Date dateCreated, Date dateUpdated) {
		this.projectId = projectId;
		this.cocCode = cocCode;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_coc_id", unique = true, nullable = false)
	public Integer getProjectCocId() {
		return this.projectCocId;
	}

	public void setProjectCocId(Integer projectCocId) {
		this.projectCocId = projectCocId;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

	@Column(name = "coc_code")
	public String getCocCode() {
		return this.cocCode;
	}

	public void setCocCode(String cocCode) {
		this.cocCode = cocCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_updated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
