package org.openhmis.domain;

// Generated Aug 4, 2015 11:17:14 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProjectInventory generated by hbm2java
 */
@Entity
@Table(name = "TMP_PROJECT_INVENTORY", catalog = "openhmis")
public class TmpProjectInventory implements java.io.Serializable {

	private Integer inventoryId;
	private Integer projectCoCid;
	private Date informationDate;
	private Integer householdType;
	private Integer bedType;
	private Integer availability;
	private Integer unitInventory;
	private Integer bedInventory;
	private Integer chBedInventory;
	private Integer vetBedInventory;
	private Integer youthBedInventory;
	private Integer youthAgeGroup;
	private Date inventoryStartDate;
	private Date inventoryEndDate;
	private Integer participatingBeds;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpProjectInventory() {
	}

	public TmpProjectInventory(Integer projectCoCid, Date informationDate,
			Integer householdType, Integer bedType, Integer availability,
			Integer unitInventory, Integer bedInventory,
			Integer chBedInventory, Integer vetBedInventory,
			Integer youthBedInventory, Integer youthAgeGroup,
			Date inventoryStartDate, Date inventoryEndDate,
			Integer participatingBeds, Date dateCreated, Date dateUpdated) {
		this.projectCoCid = projectCoCid;
		this.informationDate = informationDate;
		this.householdType = householdType;
		this.bedType = bedType;
		this.availability = availability;
		this.unitInventory = unitInventory;
		this.bedInventory = bedInventory;
		this.chBedInventory = chBedInventory;
		this.vetBedInventory = vetBedInventory;
		this.youthBedInventory = youthBedInventory;
		this.youthAgeGroup = youthAgeGroup;
		this.inventoryStartDate = inventoryStartDate;
		this.inventoryEndDate = inventoryEndDate;
		this.participatingBeds = participatingBeds;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "inventoryId", unique = true, nullable = false)
	public Integer getInventoryId() {
		return this.inventoryId;
	}

	public void setInventoryId(Integer inventoryId) {
		this.inventoryId = inventoryId;
	}

	@Column(name = "projectCoCId")
	public Integer getProjectCoCid() {
		return this.projectCoCid;
	}

	public void setProjectCoCid(Integer projectCoCid) {
		this.projectCoCid = projectCoCid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "informationDate", length = 10)
	public Date getInformationDate() {
		return this.informationDate;
	}

	public void setInformationDate(Date informationDate) {
		this.informationDate = informationDate;
	}

	@Column(name = "householdType")
	public Integer getHouseholdType() {
		return this.householdType;
	}

	public void setHouseholdType(Integer householdType) {
		this.householdType = householdType;
	}

	@Column(name = "bedType")
	public Integer getBedType() {
		return this.bedType;
	}

	public void setBedType(Integer bedType) {
		this.bedType = bedType;
	}

	@Column(name = "availability")
	public Integer getAvailability() {
		return this.availability;
	}

	public void setAvailability(Integer availability) {
		this.availability = availability;
	}

	@Column(name = "unitInventory")
	public Integer getUnitInventory() {
		return this.unitInventory;
	}

	public void setUnitInventory(Integer unitInventory) {
		this.unitInventory = unitInventory;
	}

	@Column(name = "bedInventory")
	public Integer getBedInventory() {
		return this.bedInventory;
	}

	public void setBedInventory(Integer bedInventory) {
		this.bedInventory = bedInventory;
	}

	@Column(name = "chBedInventory")
	public Integer getChBedInventory() {
		return this.chBedInventory;
	}

	public void setChBedInventory(Integer chBedInventory) {
		this.chBedInventory = chBedInventory;
	}

	@Column(name = "vetBedInventory")
	public Integer getVetBedInventory() {
		return this.vetBedInventory;
	}

	public void setVetBedInventory(Integer vetBedInventory) {
		this.vetBedInventory = vetBedInventory;
	}

	@Column(name = "youthBedInventory")
	public Integer getYouthBedInventory() {
		return this.youthBedInventory;
	}

	public void setYouthBedInventory(Integer youthBedInventory) {
		this.youthBedInventory = youthBedInventory;
	}

	@Column(name = "youthAgeGroup")
	public Integer getYouthAgeGroup() {
		return this.youthAgeGroup;
	}

	public void setYouthAgeGroup(Integer youthAgeGroup) {
		this.youthAgeGroup = youthAgeGroup;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inventoryStartDate", length = 10)
	public Date getInventoryStartDate() {
		return this.inventoryStartDate;
	}

	public void setInventoryStartDate(Date inventoryStartDate) {
		this.inventoryStartDate = inventoryStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "inventoryEndDate", length = 10)
	public Date getInventoryEndDate() {
		return this.inventoryEndDate;
	}

	public void setInventoryEndDate(Date inventoryEndDate) {
		this.inventoryEndDate = inventoryEndDate;
	}

	@Column(name = "participatingBeds")
	public Integer getParticipatingBeds() {
		return this.participatingBeds;
	}

	public void setParticipatingBeds(Integer participatingBeds) {
		this.participatingBeds = participatingBeds;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
