REM INSERTING into PATH_CODE_WAR_ZONE
SET DEFINE OFF;
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Europe',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','North Africa',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Vietnam',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Laos and Cambodia',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','South China Sea',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','China, Burma, India',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','Korea',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','South Pacific',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Persian Gulf',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,'A','Other',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,'A','Don''t Know',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'A','Refused',null,null);
Insert into PATH_CODE_WAR_ZONE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,'A','Afghanistan',null,null);
