REM INSERTING into PATH_CODE_HEALTH_STATUS
SET DEFINE OFF;
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Client refused',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Excellent',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','Very Good',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Good',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Fair',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Poor',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Client doesn''t  know',null,null);
Insert into PATH_CODE_HEALTH_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data not collected',null,null);
