REM INSERTING into PATH_CODE_OTHERID_TYPE
SET DEFINE OFF;
Insert into PATH_CODE_OTHERID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Other',null,null);
Insert into PATH_CODE_OTHERID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','State ID',null,null);
