REM INSERTING into PATH_CODE_GENDER
SET DEFINE OFF;
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (3,'A','Transgender Male to Female',null,null,4);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (4,'A','Transgender Female to Male',null,null,5);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (5,'A','Other',null,null,6);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (8,'A','Client Doesn''t Know',null,null,7);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (9,'A','Client refused',null,null,8);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (2,'A','Female',null,null,3);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (1,'A','Male',null,null,2);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (0,'A','(Select)',null,null,1);
Insert into PATH_CODE_GENDER (CODE_KEY,STATUS,GENDER,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (99,'A','Data Not Collected',null,null,9);
