REM INSERTING into PATH_CODE_ENROLLMENT_STATUS
SET DEFINE OFF;
Insert into PATH_CODE_ENROLLMENT_STATUS (CODE_KEY,STATUS,DESCRIPTION,MIGRATION_FLAG) values (0,'A','No',null);
Insert into PATH_CODE_ENROLLMENT_STATUS (CODE_KEY,STATUS,DESCRIPTION,MIGRATION_FLAG) values (1,'A','Yes',null);
Insert into PATH_CODE_ENROLLMENT_STATUS (CODE_KEY,STATUS,DESCRIPTION,MIGRATION_FLAG) values (8,'A','Don''t Know',null);
Insert into PATH_CODE_ENROLLMENT_STATUS (CODE_KEY,STATUS,DESCRIPTION,MIGRATION_FLAG) values (9,'A','Refused',null);
