REM INSERTING into PATH_CODE_DISCHARGE_STATUS
SET DEFINE OFF;
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Honorable',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','General',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'I','Medical',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Bad conduct',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Dishonorable',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Other than honorable conditions',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Client Doesn''t Know',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Client refused',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data not collected',null,null);
Insert into PATH_CODE_DISCHARGE_STATUS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','Uncharacterized',null,null);
