REM INSERTING into PATH_CODE_MILITARY_BRANCH
SET DEFINE OFF;
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Army',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','Air Force',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Navy',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Marines',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'I','Other',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Client Doesn''t Know',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Client refused',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data not collected',null,null);
Insert into PATH_CODE_MILITARY_BRANCH (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Coast Guard',null,null);
