REM INSERTING into PATH_CODE_YESNO
SET DEFINE OFF;
Insert into PATH_CODE_YESNO (CODE_KEY,STATUS,DESCRIPTION) values (1,'A','Yes');
Insert into PATH_CODE_YESNO (CODE_KEY,STATUS,DESCRIPTION) values (0,'A','No');
