REM INSERTING into PATH_CODE_FUNDING_SOURCE
SET DEFINE OFF;
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'A','Other',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Continuum of Care (HUD)',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','DCA ESG',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','DHR MHDDAD',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','DHR Family Violence',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Medicaid',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,'A','FEMA',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','CDBG',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','United Way (Metro Atlanta)',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','United Way (Other)',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Regional Homeless Commission (Metro Atl)',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,'A','Chatham-Savannah Homeless Authority',null,null);
Insert into PATH_CODE_FUNDING_SOURCE (CODE_KEY,STATUS,CODE_NAME,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,'A','Salvation Army',null,null);
