REM INSERTING into PATH_CODE_ETHNICITY
SET DEFINE OFF;
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (104,'A','Non-Hispanic/Non-Latino',null,null,2);
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (105,'A','Hispanic/Latino',null,null,1);
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (0,'A','(Select)',null,null,1);
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (8,'A','Client Doesn''t Know',null,null,3);
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (9,'A','Client refused',null,null,4);
Insert into PATH_CODE_ETHNICITY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (99,'A','Data Not Collected',null,null,5);
