REM INSERTING into PATH_CODE_PROGRAM_TYPE
SET DEFINE OFF;
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (8,'A','Safe Haven','Y ','Safe Haven',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (9,'A','PH - Permanent Housing Only','Y ','PH Only',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (10,'A','PSH - Housing with Services (no disability required for entry)','Y ','PSH (No Disability)',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (11,'A','Day Shelter','N ','Day Shelter',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (12,'A','Homelessness Prevention','N ','Prevention',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (13,'A','PH - Rapid Re-Housing','Y ','RapidReHousing',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (14,'A','Coordinated Assessment','N ','Coord. Assess.',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (1,'A','Emergency Shelter','Y ','ES',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (2,'A','Transitional housing','Y ','TH',null,null,'Y ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (3,'A','PSH - Permanent Supportive Housing (disability required for entry)','Y ','PSH (Disability)',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (4,'A','Street Outreach','N ','Outreach',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (5,'I','HPRP (Retired)','N ','HPRP',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (6,'A','Services Only','N ','Services Only',null,null,'N ');
Insert into PATH_CODE_PROGRAM_TYPE (CODE_KEY,STATUS,DESCRIPTION,RESIDENTIAL,SHORT_DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,IS_HUD_PROGRAM) values (7,'A','Other','N ','Other',null,null,'N ');
