REM INSERTING into PATH_CODE_ALL_RACE
SET DEFINE OFF;
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (15,null,'Don''t Know',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (16,null,'Refused',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Asian',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Black or African American',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','Amer-Indian or Alaskan',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','White',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Pacific Islander',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (14,'A','Other Race or Other Multi-Race',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,null,'Amer-Ind/Alaskan & White',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,null,'Asian & White',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,null,'Black/Afr-American & White',null,null);
Insert into PATH_CODE_ALL_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,null,'Amer-Ind/Alaskan & Black',null,null);
