REM INSERTING into PATH_CODE_RACE
SET DEFINE OFF;
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (15,'A','Client Doesn''t Know',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (16,'A','Client refused',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Asian',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Black or African American',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','American Indian or Alaska Native',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','White',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Native Hawaiian or Other  Pacific Islander',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (14,'A','Other',null,null);
Insert into PATH_CODE_RACE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data Not Collected',null,null);
