REM INSERTING into PATH_CODE_VETERAN
SET DEFINE OFF;
Insert into PATH_CODE_VETERAN (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (0,'A','No',null,null,1);
Insert into PATH_CODE_VETERAN (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (1,'A','Yes',null,null,2);
Insert into PATH_CODE_VETERAN (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (8,'A','Client Doesn''t Know',null,null,3);
Insert into PATH_CODE_VETERAN (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (9,'A','Client Refused',null,null,4);
Insert into PATH_CODE_VETERAN (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (99,'A','Data Not Collected',null,null,5);
