REM INSERTING into PATH_CODE_LENGTH_OF_STAY
SET DEFINE OFF;
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (1,'I','one week or less',null,null,null);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (2,'A','More than one week but less than one month',null,null,30);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (3,'A','One to three months',null,null,40);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (4,'A','More than three months but less than one year',null,null,50);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (5,'A','One year or longer',null,null,60);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (8,'A','Client Doesn''t Know',null,null,70);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (9,'A','Client Refused',null,null,80);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (10,'A','One day or less',null,null,10);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (11,'A','Two days to one week',null,null,20);
Insert into PATH_CODE_LENGTH_OF_STAY (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (99,'A','Data Not Collected',null,null,90);
