package org.openhmis.domain;

// Generated Jul 29, 2015 7:35:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PathClientProgram generated by hbm2java
 */
@Entity
@Table(name = "PATH_CLIENT_PROGRAM")
public class PathClientProgram implements java.io.Serializable {

	private Integer programKey;
	private Integer clientKey;
	private Date entryDate;
	private Integer entryCashGk;
	private Integer entryNoncashGk;
	private Date exitDate;
	private Integer exitCashGk;
	private Integer exitNoncashGk;
	private Integer programNameKey;
	private Integer destinationKey;
	private Integer reasonLeavingKey;
	private Date createDate;
	private Integer createUserKey;
	private Date updateDate;
	private Integer updateUserKey;
	private Character status;
	private Integer tenureKey;
	private Integer subsidyKey;
	private Character recActive;
	private String subsidyOthers;
	private String reasonLeavingOthers;
	private String destinationOthers;
	private Integer housingStatusKey;
	private String countyname;
	private Date engagementDate;
	private Integer barcodeProfileKey;
	private Date updateTimestamp;
	private String migrationFlag;
	private Integer annualCashGk;
	private Integer annualNoncashGk;

	public PathClientProgram() {
	}

	public PathClientProgram(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	public PathClientProgram(Integer clientKey, Date entryDate,
			Integer entryCashGk, Integer entryNoncashGk, Date exitDate,
			Integer exitCashGk, Integer exitNoncashGk, Integer programNameKey,
			Integer destinationKey, Integer reasonLeavingKey, Date createDate,
			Integer createUserKey, Date updateDate, Integer updateUserKey,
			Character status, Integer tenureKey, Integer subsidyKey,
			Character recActive, String subsidyOthers,
			String reasonLeavingOthers, String destinationOthers,
			Integer housingStatusKey, String countyname, Date engagementDate,
			Integer barcodeProfileKey, Date updateTimestamp,
			String migrationFlag, Integer annualCashGk, Integer annualNoncashGk) {
		this.clientKey = clientKey;
		this.entryDate = entryDate;
		this.entryCashGk = entryCashGk;
		this.entryNoncashGk = entryNoncashGk;
		this.exitDate = exitDate;
		this.exitCashGk = exitCashGk;
		this.exitNoncashGk = exitNoncashGk;
		this.programNameKey = programNameKey;
		this.destinationKey = destinationKey;
		this.reasonLeavingKey = reasonLeavingKey;
		this.createDate = createDate;
		this.createUserKey = createUserKey;
		this.updateDate = updateDate;
		this.updateUserKey = updateUserKey;
		this.status = status;
		this.tenureKey = tenureKey;
		this.subsidyKey = subsidyKey;
		this.recActive = recActive;
		this.subsidyOthers = subsidyOthers;
		this.reasonLeavingOthers = reasonLeavingOthers;
		this.destinationOthers = destinationOthers;
		this.housingStatusKey = housingStatusKey;
		this.countyname = countyname;
		this.engagementDate = engagementDate;
		this.barcodeProfileKey = barcodeProfileKey;
		this.updateTimestamp = updateTimestamp;
		this.migrationFlag = migrationFlag;
		this.annualCashGk = annualCashGk;
		this.annualNoncashGk = annualNoncashGk;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PROGRAM_KEY", unique = true, nullable = false)
	public Integer getProgramKey() {
		return this.programKey;
	}

	public void setProgramKey(Integer programKey) {
		this.programKey = programKey;
	}

	@Column(name = "CLIENT_KEY")
	public Integer getClientKey() {
		return this.clientKey;
	}

	public void setClientKey(Integer clientKey) {
		this.clientKey = clientKey;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENTRY_DATE", length = 10)
	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	@Column(name = "ENTRY_CASH_GK")
	public Integer getEntryCashGk() {
		return this.entryCashGk;
	}

	public void setEntryCashGk(Integer entryCashGk) {
		this.entryCashGk = entryCashGk;
	}

	@Column(name = "ENTRY_NONCASH_GK")
	public Integer getEntryNoncashGk() {
		return this.entryNoncashGk;
	}

	public void setEntryNoncashGk(Integer entryNoncashGk) {
		this.entryNoncashGk = entryNoncashGk;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXIT_DATE", length = 10)
	public Date getExitDate() {
		return this.exitDate;
	}

	public void setExitDate(Date exitDate) {
		this.exitDate = exitDate;
	}

	@Column(name = "EXIT_CASH_GK")
	public Integer getExitCashGk() {
		return this.exitCashGk;
	}

	public void setExitCashGk(Integer exitCashGk) {
		this.exitCashGk = exitCashGk;
	}

	@Column(name = "EXIT_NONCASH_GK")
	public Integer getExitNoncashGk() {
		return this.exitNoncashGk;
	}

	public void setExitNoncashGk(Integer exitNoncashGk) {
		this.exitNoncashGk = exitNoncashGk;
	}

	@Column(name = "PROGRAM_NAME_KEY")
	public Integer getProgramNameKey() {
		return this.programNameKey;
	}

	public void setProgramNameKey(Integer programNameKey) {
		this.programNameKey = programNameKey;
	}

	@Column(name = "DESTINATION_KEY")
	public Integer getDestinationKey() {
		return this.destinationKey;
	}

	public void setDestinationKey(Integer destinationKey) {
		this.destinationKey = destinationKey;
	}

	@Column(name = "REASON_LEAVING_KEY")
	public Integer getReasonLeavingKey() {
		return this.reasonLeavingKey;
	}

	public void setReasonLeavingKey(Integer reasonLeavingKey) {
		this.reasonLeavingKey = reasonLeavingKey;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_DATE", length = 10)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "CREATE_USER_KEY")
	public Integer getCreateUserKey() {
		return this.createUserKey;
	}

	public void setCreateUserKey(Integer createUserKey) {
		this.createUserKey = createUserKey;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UPDATE_DATE", length = 10)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_USER_KEY")
	public Integer getUpdateUserKey() {
		return this.updateUserKey;
	}

	public void setUpdateUserKey(Integer updateUserKey) {
		this.updateUserKey = updateUserKey;
	}

	@Column(name = "STATUS", length = 1)
	public Character getStatus() {
		return this.status;
	}

	public void setStatus(Character status) {
		this.status = status;
	}

	@Column(name = "TENURE_KEY")
	public Integer getTenureKey() {
		return this.tenureKey;
	}

	public void setTenureKey(Integer tenureKey) {
		this.tenureKey = tenureKey;
	}

	@Column(name = "SUBSIDY_KEY")
	public Integer getSubsidyKey() {
		return this.subsidyKey;
	}

	public void setSubsidyKey(Integer subsidyKey) {
		this.subsidyKey = subsidyKey;
	}

	@Column(name = "REC_ACTIVE", length = 1)
	public Character getRecActive() {
		return this.recActive;
	}

	public void setRecActive(Character recActive) {
		this.recActive = recActive;
	}

	@Column(name = "SUBSIDY_OTHERS", length = 50)
	public String getSubsidyOthers() {
		return this.subsidyOthers;
	}

	public void setSubsidyOthers(String subsidyOthers) {
		this.subsidyOthers = subsidyOthers;
	}

	@Column(name = "REASON_LEAVING_OTHERS", length = 50)
	public String getReasonLeavingOthers() {
		return this.reasonLeavingOthers;
	}

	public void setReasonLeavingOthers(String reasonLeavingOthers) {
		this.reasonLeavingOthers = reasonLeavingOthers;
	}

	@Column(name = "DESTINATION_OTHERS", length = 50)
	public String getDestinationOthers() {
		return this.destinationOthers;
	}

	public void setDestinationOthers(String destinationOthers) {
		this.destinationOthers = destinationOthers;
	}

	@Column(name = "HOUSING_STATUS_KEY")
	public Integer getHousingStatusKey() {
		return this.housingStatusKey;
	}

	public void setHousingStatusKey(Integer housingStatusKey) {
		this.housingStatusKey = housingStatusKey;
	}

	@Column(name = "COUNTYNAME", length = 64)
	public String getCountyname() {
		return this.countyname;
	}

	public void setCountyname(String countyname) {
		this.countyname = countyname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENGAGEMENT_DATE", length = 10)
	public Date getEngagementDate() {
		return this.engagementDate;
	}

	public void setEngagementDate(Date engagementDate) {
		this.engagementDate = engagementDate;
	}

	@Column(name = "BARCODE_PROFILE_KEY")
	public Integer getBarcodeProfileKey() {
		return this.barcodeProfileKey;
	}

	public void setBarcodeProfileKey(Integer barcodeProfileKey) {
		this.barcodeProfileKey = barcodeProfileKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_TIMESTAMP", nullable = false, length = 19)
	public Date getUpdateTimestamp() {
		return this.updateTimestamp;
	}

	public void setUpdateTimestamp(Date updateTimestamp) {
		this.updateTimestamp = updateTimestamp;
	}

	@Column(name = "MIGRATION_FLAG", length = 2)
	public String getMigrationFlag() {
		return this.migrationFlag;
	}

	public void setMigrationFlag(String migrationFlag) {
		this.migrationFlag = migrationFlag;
	}

	@Column(name = "ANNUAL_CASH_GK")
	public Integer getAnnualCashGk() {
		return this.annualCashGk;
	}

	public void setAnnualCashGk(Integer annualCashGk) {
		this.annualCashGk = annualCashGk;
	}

	@Column(name = "ANNUAL_NONCASH_GK")
	public Integer getAnnualNoncashGk() {
		return this.annualNoncashGk;
	}

	public void setAnnualNoncashGk(Integer annualNoncashGk) {
		this.annualNoncashGk = annualNoncashGk;
	}

}
