package org.openhmis.domain;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.openhmis.code.ConsentRequestType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT_FIELD")
public class TmpConsentField implements java.io.Serializable {

	private Integer consentFieldId;
	private TmpConsent consent;
	private Integer fieldCode;
	private Integer requestTypeCode;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpConsentField() {
	}

	public TmpConsentField(Integer consentFieldId, TmpConsent consent, Integer fieldCode, Integer requestTypeCode, Date dateCreated, Date dateUpdated) {
		this.consentFieldId = consentFieldId;
		this.consent = consent;
		this.fieldCode = fieldCode;
		this.requestTypeCode = requestTypeCode;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentFieldId", unique = true, nullable = false)
	public Integer getConsentFieldId() {
		return this.consentFieldId;
	}

	public void setConsentFieldId(Integer consentFieldId) {
		this.consentFieldId = consentFieldId;
	}

    @ManyToOne
    @JoinColumn(name="consentId")
	public TmpConsent getConsent() {
		return this.consent;
	}

	public void setConsent(TmpConsent consent) {
		this.consent = consent;
	}

	@Column(name = "fieldCode")
	public Integer getFieldCode() {
		return this.fieldCode;
	}

	public void setFieldCode(Integer fieldCode) {
		this.fieldCode = fieldCode;
	}

	@Column(name = "requestTypeCode")
	public Integer getRequestTypeCode() {
		return this.requestTypeCode;
	}

	public void setRequestTypeCode(Integer requestTypeCode) {
		this.requestTypeCode = requestTypeCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
