package org.openhmis.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpOrganization generated by hbm2java
 */
@Entity
@Table(name = "TMP_COC")
public class TmpCoC implements java.io.Serializable {

	private Integer coCId;
	private String coCName;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpCoC() {
	}

	public TmpCoC(String coCName, Date dateCreated,
			Date dateUpdated) {
		this.coCName = coCName;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "coCId", unique = true, nullable = false)
	public Integer getCoCId() {
		return this.coCId;
	}

	public void setCoCId(Integer coCId) {
		this.coCId = coCId;
	}

	@Column(name = "coCName")
	public String getCoCName() {
		return this.coCName;
	}

	public void setCoCName(String coCName) {
		this.coCName = coCName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
