package org.openhmis.domain;



// Generated Aug 5, 2015 10:00:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT_ORGANIZATION")
public class TmpConsentOrganization implements java.io.Serializable {

	private Integer consentOrganizationId;
	private Integer consentId;
	private Integer organizationId;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpConsentOrganization() {
	}

	public TmpConsentOrganization(Integer consentOrganizationId, Integer consentId, Date dateCreated, Date dateUpdated) {
		this.consentOrganizationId = consentOrganizationId;
		this.consentId = consentId;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentOrganizationId", unique = true, nullable = false)
	public Integer getConsentOrganizationId() {
		return this.consentOrganizationId;
	}

	public void setConsentOrganizationId(Integer consentOrganizationId) {
		this.consentOrganizationId = consentOrganizationId;
	}

	@Column(name = "consentId")
	public Integer getConsentId() {
		return this.consentId;
	}

	public void setConsentId(Integer consentId) {
		this.consentId = consentId;
	}

	@Column(name = "organizationId")
	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
