package org.openhmis.domain;

import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT")
public class TmpConsent implements java.io.Serializable {

	private Integer consentId;
	private TmpUser submitter;
	private PathClient client;
	private Integer approvalStatusCode;
	private Date dateProcessed;
	private Date dateCreated;
	private Date dateUpdated;
    private Set<TmpConsentCoC> consentCoCs;
    private Set<TmpConsentField> consentFields;
    private Set<TmpConsentOrganization> consentOrganizations;
	

    @OneToMany
    @JoinColumn( name="consentId")
    public Set<TmpConsentCoC> getConsentCoCs() {
    	return this.consentCoCs;
    }
    public void setConsentCoCs(Set<TmpConsentCoC> consentCoCs) {
    	this.consentCoCs = consentCoCs;
    }

    @OneToMany
    @JoinColumn( name="consentId")
    public Set<TmpConsentField> getConsentFields() {
    	return this.consentFields;
    }
    public void setConsentFields(Set<TmpConsentField> consentFields) {
    	this.consentFields = consentFields;
    }
    
    @OneToMany
    @JoinColumn( name="consentId")
    public Set<TmpConsentOrganization> getConsentOrganizations() {
    	return this.consentOrganizations;
    }
    public void setConsentOrganizations(Set<TmpConsentOrganization> consentOrganizations) {
    	this.consentOrganizations = consentOrganizations;
    }

	public TmpConsent() {
	}

	public TmpConsent(Integer consentId, TmpUser submitter, PathClient client, Date dateProcessed, Date dateCreated, Date dateUpdated) {
		this.consentId = consentId;
		this.submitter = submitter;
		this.client = client;
		this.dateProcessed = dateProcessed;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentId", unique = true, nullable = false)
	public Integer getConsentId() {
		return this.consentId;
	}

	public void setConsentId(Integer consentId) {
		this.consentId = consentId;
	}

    @ManyToOne
    @JoinColumn(name="submitterId")
	public TmpUser getSubmitter() {
		return this.submitter;
	}

	public void setSubmitter(TmpUser submitter) {
		this.submitter = submitter;
	}

    @ManyToOne
    @JoinColumn(name="clientKey")
	public PathClient getClient() {
		return this.client;
	}

	public void setClient(PathClient client) {
		this.client = client;
	}

	@Column(name = "approvalStatusCode")
	public Integer getApprovalStatusCode() {
		return this.approvalStatusCode;
	}

	public void setapprovalStatusCode(Integer approvalStatusCode) {
		this.approvalStatusCode = approvalStatusCode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateProcessed", length = 10)
	public Date getDateProcessed() {
		return this.dateProcessed;
	}

	public void setDateProcessed(Date dateProcessed) {
		this.dateProcessed = dateProcessed;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
