package org.openhmis.domain;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT_FIELD")
public class TmpConsentField implements java.io.Serializable {

	private Integer consentFieldId;
	private Integer consentId;
	private String fieldName;
	private Integer requestType;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpConsentField() {
	}

	public TmpConsentField(Integer consentFieldId, Integer consentId, String fieldName, Integer requestType, Date dateCreated, Date dateUpdated) {
		this.consentFieldId = consentFieldId;
		this.consentId = consentId;
		this.fieldName = fieldName;
		this.requestType = requestType;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentCoCId", unique = true, nullable = false)
	public Integer getConsentFieldId() {
		return this.consentFieldId;
	}

	public void setConsentFieldId(Integer consentFieldId) {
		this.consentFieldId = consentFieldId;
	}

	@Column(name = "consentId")
	public Integer getConsentId() {
		return this.consentId;
	}

	public void setConsentId(Integer consentId) {
		this.consentId = consentId;
	}

	@Column(name = "fieldName")
	public String getFieldName() {
		return this.fieldName;
	}

	public void setFieldName(String fieldName) {
		this.fieldName = fieldName;
	}

	@Column(name = "requestType")
	public Integer getRequestType() {
		return this.requestType;
	}

	public void setRequestType(Integer requestType) {
		this.requestType = requestType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
