package org.openhmis.domain;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT_COC")
public class TmpConsentCoC implements java.io.Serializable {

	private Integer consentCoCId;
	private TmpConsent consent;
	private TmpCoC coC;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpConsentCoC() {
	}

	public TmpConsentCoC(Integer consentCoCId, TmpConsent consent, TmpCoC coC, Date dateCreated, Date dateUpdated) {
		this.consentCoCId = consentCoCId;
		this.consent = consent;
		this.coC = coC;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentCoCId", unique = true, nullable = false)
	public Integer getConsentCoCId() {
		return this.consentCoCId;
	}

	public void setConsentCoCId(Integer consentCoCId) {
		this.consentCoCId = consentCoCId;
	}

    @ManyToOne
    @JoinColumn(name="consentId")
	public TmpConsent getConsent() {
		return this.consent;
	}

	public void setConsent(TmpConsent consent) {
		this.consent = consent;
	}

    @ManyToOne
    @JoinColumn(name="coCId")
	public TmpCoC getCoC() {
		return this.coC;
	}

	public void setCoC(TmpCoC coC) {
		this.coC = coC;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
