package org.openhmis.domain;



// Generated Aug 5, 2015 10:00:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpContact generated by hbm2java
 */
@Entity
@Table(name = "TMP_CONSENT_ORGANIZATION")
public class TmpConsentOrganization implements java.io.Serializable {

	private Integer consentOrganizationId;
	private TmpConsent consent;
	private TmpOrganization organization;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpConsentOrganization() {
	}

	public TmpConsentOrganization(Integer consentOrganizationId, TmpConsent consent, TmpOrganization organization, Date dateCreated, Date dateUpdated) {
		this.consentOrganizationId = consentOrganizationId;
		this.consent = consent;
		this.organization = organization;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "consentOrganizationId", unique = true, nullable = false)
	public Integer getConsentOrganizationId() {
		return this.consentOrganizationId;
	}

	public void setConsentOrganizationId(Integer consentOrganizationId) {
		this.consentOrganizationId = consentOrganizationId;
	}

	@Column(name = "consentId")
	public TmpConsent getConsent() {
		return this.consent;
	}

	public void setConsent(TmpConsent consent) {
		this.consent = consent;
	}

    @ManyToOne
	@JoinColumn(name = "organizationId")
	public TmpOrganization getOrganization() {
		return this.organization;
	}

	public void setOrganization(TmpOrganization organization) {
		this.organization = organization;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
