package org.openhmis.domain;

// Generated Aug 5, 2015 10:00:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpHealthInsurance generated by hbm2java
 */
@Entity
@Table(name = "TMP_HEALTH_INSURANCE")
public class TmpHealthInsurance implements java.io.Serializable {

	private Integer healthInsuranceId;
	private Integer enrollmentId;
	private Date informationDate;
	private Integer insuranceFromAnySource;
	private Integer medicaid;
	private Integer noMedicaidReason;
	private Integer medicare;
	private Integer noMedicareReason;
	private Integer schip;
	private Integer noSchipReason;
	private Integer vaMedicalServices;
	private Integer noVaMedReason;
	private Integer employerProvided;
	private Integer noEmployerProvidedReason;
	private Integer cobra;
	private Integer noCobraReason;
	private Integer pay;
	private Integer noPayReason;
	private Integer stateHealthIns;
	private Integer noStateHealthInsReason;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpHealthInsurance() {
	}

	public TmpHealthInsurance(Integer enrollmentId, Date informationDate,
			Integer insuranceFromAnySource, Integer medicaid,
			Integer noMedicaidReason, Integer medicare,
			Integer noMedicareReason, Integer schip, Integer noSchipReason,
			Integer vaMedicalServices, Integer noVaMedReason,
			Integer employerProvided, Integer noEmployerProvidedReason,
			Integer cobra, Integer noCobraReason, Integer pay,
			Integer noPayReason, Integer stateHealthIns,
			Integer noStateHealthInsReason, Date dateCreated, Date dateUpdated) {
		this.enrollmentId = enrollmentId;
		this.informationDate = informationDate;
		this.insuranceFromAnySource = insuranceFromAnySource;
		this.medicaid = medicaid;
		this.noMedicaidReason = noMedicaidReason;
		this.medicare = medicare;
		this.noMedicareReason = noMedicareReason;
		this.schip = schip;
		this.noSchipReason = noSchipReason;
		this.vaMedicalServices = vaMedicalServices;
		this.noVaMedReason = noVaMedReason;
		this.employerProvided = employerProvided;
		this.noEmployerProvidedReason = noEmployerProvidedReason;
		this.cobra = cobra;
		this.noCobraReason = noCobraReason;
		this.pay = pay;
		this.noPayReason = noPayReason;
		this.stateHealthIns = stateHealthIns;
		this.noStateHealthInsReason = noStateHealthInsReason;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "healthInsuranceId", unique = true, nullable = false)
	public Integer getHealthInsuranceId() {
		return this.healthInsuranceId;
	}

	public void setHealthInsuranceId(Integer healthInsuranceId) {
		this.healthInsuranceId = healthInsuranceId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "informationDate", length = 10)
	public Date getInformationDate() {
		return this.informationDate;
	}

	public void setInformationDate(Date informationDate) {
		this.informationDate = informationDate;
	}

	@Column(name = "insuranceFromAnySource")
	public Integer getInsuranceFromAnySource() {
		return this.insuranceFromAnySource;
	}

	public void setInsuranceFromAnySource(Integer insuranceFromAnySource) {
		this.insuranceFromAnySource = insuranceFromAnySource;
	}

	@Column(name = "medicaid")
	public Integer getMedicaid() {
		return this.medicaid;
	}

	public void setMedicaid(Integer medicaid) {
		this.medicaid = medicaid;
	}

	@Column(name = "noMedicaidReason")
	public Integer getNoMedicaidReason() {
		return this.noMedicaidReason;
	}

	public void setNoMedicaidReason(Integer noMedicaidReason) {
		this.noMedicaidReason = noMedicaidReason;
	}

	@Column(name = "medicare")
	public Integer getMedicare() {
		return this.medicare;
	}

	public void setMedicare(Integer medicare) {
		this.medicare = medicare;
	}

	@Column(name = "noMedicareReason")
	public Integer getNoMedicareReason() {
		return this.noMedicareReason;
	}

	public void setNoMedicareReason(Integer noMedicareReason) {
		this.noMedicareReason = noMedicareReason;
	}

	@Column(name = "schip")
	public Integer getSchip() {
		return this.schip;
	}

	public void setSchip(Integer schip) {
		this.schip = schip;
	}

	@Column(name = "noSchipReason")
	public Integer getNoSchipReason() {
		return this.noSchipReason;
	}

	public void setNoSchipReason(Integer noSchipReason) {
		this.noSchipReason = noSchipReason;
	}

	@Column(name = "vaMedicalServices")
	public Integer getVaMedicalServices() {
		return this.vaMedicalServices;
	}

	public void setVaMedicalServices(Integer vaMedicalServices) {
		this.vaMedicalServices = vaMedicalServices;
	}

	@Column(name = "noVaMedReason")
	public Integer getNoVaMedReason() {
		return this.noVaMedReason;
	}

	public void setNoVaMedReason(Integer noVaMedReason) {
		this.noVaMedReason = noVaMedReason;
	}

	@Column(name = "employerProvided")
	public Integer getEmployerProvided() {
		return this.employerProvided;
	}

	public void setEmployerProvided(Integer employerProvided) {
		this.employerProvided = employerProvided;
	}

	@Column(name = "noEmployerProvidedReason")
	public Integer getNoEmployerProvidedReason() {
		return this.noEmployerProvidedReason;
	}

	public void setNoEmployerProvidedReason(Integer noEmployerProvidedReason) {
		this.noEmployerProvidedReason = noEmployerProvidedReason;
	}

	@Column(name = "cobra")
	public Integer getCobra() {
		return this.cobra;
	}

	public void setCobra(Integer cobra) {
		this.cobra = cobra;
	}

	@Column(name = "noCobraReason")
	public Integer getNoCobraReason() {
		return this.noCobraReason;
	}

	public void setNoCobraReason(Integer noCobraReason) {
		this.noCobraReason = noCobraReason;
	}

	@Column(name = "Pay")
	public Integer getPay() {
		return this.pay;
	}

	public void setPay(Integer pay) {
		this.pay = pay;
	}

	@Column(name = "noPayReason")
	public Integer getNoPayReason() {
		return this.noPayReason;
	}

	public void setNoPayReason(Integer noPayReason) {
		this.noPayReason = noPayReason;
	}

	@Column(name = "stateHealthIns")
	public Integer getStateHealthIns() {
		return this.stateHealthIns;
	}

	public void setStateHealthIns(Integer stateHealthIns) {
		this.stateHealthIns = stateHealthIns;
	}

	@Column(name = "noStateHealthInsReason")
	public Integer getNoStateHealthInsReason() {
		return this.noStateHealthInsReason;
	}

	public void setNoStateHealthInsReason(Integer noStateHealthInsReason) {
		this.noStateHealthInsReason = noStateHealthInsReason;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
