package org.openhmis.domain;



// Generated Aug 5, 2015 10:00:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpIncomeSource generated by hbm2java
 */
@Entity
@Table(name = "TMP_INCOME_SOURCE")
public class TmpIncomeSource implements java.io.Serializable {

	private Integer incomeSourceId;
	private Integer enrollmentId;
	private Date informationDate;
	private Integer incomeFromAnySourceCode;
	private Integer totalMonthlyIncome;
	private Integer earned;
	private Integer earnedAmount;
	private Integer unemployment;
	private Integer unemploymentAmount;
	private Integer ssi;
	private Integer ssiAmount;
	private Integer ssdi;
	private Integer ssdiAmount;
	private Integer vaDisabilityService;
	private Integer vaDisabilityServiceAmount;
	private Integer vaDisabilityNonService;
	private Integer vaDisabilityNonServiceAmount;
	private Integer disability;
	private Integer disabilityAmount;
	private Integer workerscomp;
	private Integer workersCompAmount;
	private Integer tanf;
	private Integer tanfAmount;
	private Integer ga;
	private Integer gaAmount;
	private Integer socSecRetirement;
	private Integer socSecRetirementAmount;
	private Integer pension;
	private Integer pensionAmount;
	private Integer childSupport;
	private Integer childSupportAmount;
	private Integer alimony;
	private Integer alimonyAmount;
	private Integer otherIncomeSource;
	private Integer otherIncomeAmount;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpIncomeSource() {
	}

	public TmpIncomeSource(Integer enrollmentId, Date informationDate,
			Integer incomeFromAnySourceCode, Integer totalMonthlyIncome,
			Integer earned, Integer earnedAmount, Integer unemployment,
			Integer unemploymentAmount, Integer ssi, Integer ssiAmount,
			Integer ssdi, Integer ssdiAmount, Integer vaDisabilityService,
			Integer vaDisabilityServiceAmount, Integer vaDisabilityNonService,
			Integer vaDisabilityNonServiceAmount, Integer disability,
			Integer disabilityAmount, Integer workerscomp,
			Integer workersCompAmount, Integer tanf, Integer tanfAmount,
			Integer ga, Integer gaAmount, Integer socSecRetirement,
			Integer socSecRetirementAmount, Integer pension,
			Integer pensionAmount, Integer childSupport,
			Integer childSupportAmount, Integer alimony, Integer alimonyAmount,
			Integer otherIncomeSource, Integer otherIncomeAmount,
			Date dateCreated, Date dateUpdated) {
		this.enrollmentId = enrollmentId;
		this.informationDate = informationDate;
		this.incomeFromAnySourceCode = incomeFromAnySourceCode;
		this.totalMonthlyIncome = totalMonthlyIncome;
		this.earned = earned;
		this.earnedAmount = earnedAmount;
		this.unemployment = unemployment;
		this.unemploymentAmount = unemploymentAmount;
		this.ssi = ssi;
		this.ssiAmount = ssiAmount;
		this.ssdi = ssdi;
		this.ssdiAmount = ssdiAmount;
		this.vaDisabilityService = vaDisabilityService;
		this.vaDisabilityServiceAmount = vaDisabilityServiceAmount;
		this.vaDisabilityNonService = vaDisabilityNonService;
		this.vaDisabilityNonServiceAmount = vaDisabilityNonServiceAmount;
		this.disability = disability;
		this.disabilityAmount = disabilityAmount;
		this.workerscomp = workerscomp;
		this.workersCompAmount = workersCompAmount;
		this.tanf = tanf;
		this.tanfAmount = tanfAmount;
		this.ga = ga;
		this.gaAmount = gaAmount;
		this.socSecRetirement = socSecRetirement;
		this.socSecRetirementAmount = socSecRetirementAmount;
		this.pension = pension;
		this.pensionAmount = pensionAmount;
		this.childSupport = childSupport;
		this.childSupportAmount = childSupportAmount;
		this.alimony = alimony;
		this.alimonyAmount = alimonyAmount;
		this.otherIncomeSource = otherIncomeSource;
		this.otherIncomeAmount = otherIncomeAmount;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "incomeSourceId", unique = true, nullable = false)
	public Integer getIncomeSourceId() {
		return this.incomeSourceId;
	}

	public void setIncomeSourceId(Integer incomeSourceId) {
		this.incomeSourceId = incomeSourceId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "informationDate", length = 10)
	public Date getInformationDate() {
		return this.informationDate;
	}

	public void setInformationDate(Date informationDate) {
		this.informationDate = informationDate;
	}

	@Column(name = "incomeFromAnySourceCode")
	public Integer getIncomeFromAnySourceCode() {
		return this.incomeFromAnySourceCode;
	}

	public void setIncomeFromAnySourceCode(Integer incomeFromAnySourceCode) {
		this.incomeFromAnySourceCode = incomeFromAnySourceCode;
	}

	@Column(name = "totalMonthlyIncome")
	public Integer getTotalMonthlyIncome() {
		return this.totalMonthlyIncome;
	}

	public void setTotalMonthlyIncome(Integer totalMonthlyIncome) {
		this.totalMonthlyIncome = totalMonthlyIncome;
	}

	@Column(name = "earned")
	public Integer getEarned() {
		return this.earned;
	}

	public void setEarned(Integer earned) {
		this.earned = earned;
	}

	@Column(name = "earnedAmount")
	public Integer getEarnedAmount() {
		return this.earnedAmount;
	}

	public void setEarnedAmount(Integer earnedAmount) {
		this.earnedAmount = earnedAmount;
	}

	@Column(name = "unemployment")
	public Integer getUnemployment() {
		return this.unemployment;
	}

	public void setUnemployment(Integer unemployment) {
		this.unemployment = unemployment;
	}

	@Column(name = "unemploymentAmount")
	public Integer getUnemploymentAmount() {
		return this.unemploymentAmount;
	}

	public void setUnemploymentAmount(Integer unemploymentAmount) {
		this.unemploymentAmount = unemploymentAmount;
	}

	@Column(name = "ssi")
	public Integer getSsi() {
		return this.ssi;
	}

	public void setSsi(Integer ssi) {
		this.ssi = ssi;
	}

	@Column(name = "ssiAmount")
	public Integer getSsiAmount() {
		return this.ssiAmount;
	}

	public void setSsiAmount(Integer ssiAmount) {
		this.ssiAmount = ssiAmount;
	}

	@Column(name = "ssdi")
	public Integer getSsdi() {
		return this.ssdi;
	}

	public void setSsdi(Integer ssdi) {
		this.ssdi = ssdi;
	}

	@Column(name = "ssdiAmount")
	public Integer getSsdiAmount() {
		return this.ssdiAmount;
	}

	public void setSsdiAmount(Integer ssdiAmount) {
		this.ssdiAmount = ssdiAmount;
	}

	@Column(name = "vaDisabilityService")
	public Integer getVaDisabilityService() {
		return this.vaDisabilityService;
	}

	public void setVaDisabilityService(Integer vaDisabilityService) {
		this.vaDisabilityService = vaDisabilityService;
	}

	@Column(name = "vaDisabilityServiceAmount")
	public Integer getVaDisabilityServiceAmount() {
		return this.vaDisabilityServiceAmount;
	}

	public void setVaDisabilityServiceAmount(Integer vaDisabilityServiceAmount) {
		this.vaDisabilityServiceAmount = vaDisabilityServiceAmount;
	}

	@Column(name = "vaDisabilityNonService")
	public Integer getVaDisabilityNonService() {
		return this.vaDisabilityNonService;
	}

	public void setVaDisabilityNonService(Integer vaDisabilityNonService) {
		this.vaDisabilityNonService = vaDisabilityNonService;
	}

	@Column(name = "vaDisabilityNonServiceAmount")
	public Integer getVaDisabilityNonServiceAmount() {
		return this.vaDisabilityNonServiceAmount;
	}

	public void setVaDisabilityNonServiceAmount(
			Integer vaDisabilityNonServiceAmount) {
		this.vaDisabilityNonServiceAmount = vaDisabilityNonServiceAmount;
	}

	@Column(name = "Disability")
	public Integer getDisability() {
		return this.disability;
	}

	public void setDisability(Integer disability) {
		this.disability = disability;
	}

	@Column(name = "DisabilityAmount")
	public Integer getDisabilityAmount() {
		return this.disabilityAmount;
	}

	public void setDisabilityAmount(Integer disabilityAmount) {
		this.disabilityAmount = disabilityAmount;
	}

	@Column(name = "workerscomp")
	public Integer getWorkerscomp() {
		return this.workerscomp;
	}

	public void setWorkerscomp(Integer workerscomp) {
		this.workerscomp = workerscomp;
	}

	@Column(name = "workersCompAmount")
	public Integer getWorkersCompAmount() {
		return this.workersCompAmount;
	}

	public void setWorkersCompAmount(Integer workersCompAmount) {
		this.workersCompAmount = workersCompAmount;
	}

	@Column(name = "tanf")
	public Integer getTanf() {
		return this.tanf;
	}

	public void setTanf(Integer tanf) {
		this.tanf = tanf;
	}

	@Column(name = "tanfAmount")
	public Integer getTanfAmount() {
		return this.tanfAmount;
	}

	public void setTanfAmount(Integer tanfAmount) {
		this.tanfAmount = tanfAmount;
	}

	@Column(name = "ga")
	public Integer getGa() {
		return this.ga;
	}

	public void setGa(Integer ga) {
		this.ga = ga;
	}

	@Column(name = "gaAmount")
	public Integer getGaAmount() {
		return this.gaAmount;
	}

	public void setGaAmount(Integer gaAmount) {
		this.gaAmount = gaAmount;
	}

	@Column(name = "socSecRetirement")
	public Integer getSocSecRetirement() {
		return this.socSecRetirement;
	}

	public void setSocSecRetirement(Integer socSecRetirement) {
		this.socSecRetirement = socSecRetirement;
	}

	@Column(name = "socSecRetirementAmount")
	public Integer getSocSecRetirementAmount() {
		return this.socSecRetirementAmount;
	}

	public void setSocSecRetirementAmount(Integer socSecRetirementAmount) {
		this.socSecRetirementAmount = socSecRetirementAmount;
	}

	@Column(name = "pension")
	public Integer getPension() {
		return this.pension;
	}

	public void setPension(Integer pension) {
		this.pension = pension;
	}

	@Column(name = "pensionAmount")
	public Integer getPensionAmount() {
		return this.pensionAmount;
	}

	public void setPensionAmount(Integer pensionAmount) {
		this.pensionAmount = pensionAmount;
	}

	@Column(name = "childSupport")
	public Integer getChildSupport() {
		return this.childSupport;
	}

	public void setChildSupport(Integer childSupport) {
		this.childSupport = childSupport;
	}

	@Column(name = "childSupportAmount")
	public Integer getChildSupportAmount() {
		return this.childSupportAmount;
	}

	public void setChildSupportAmount(Integer childSupportAmount) {
		this.childSupportAmount = childSupportAmount;
	}

	@Column(name = "alimony")
	public Integer getAlimony() {
		return this.alimony;
	}

	public void setAlimony(Integer alimony) {
		this.alimony = alimony;
	}

	@Column(name = "alimonyAmount")
	public Integer getAlimonyAmount() {
		return this.alimonyAmount;
	}

	public void setAlimonyAmount(Integer alimonyAmount) {
		this.alimonyAmount = alimonyAmount;
	}

	@Column(name = "otherIncomeSource")
	public Integer getOtherIncomeSource() {
		return this.otherIncomeSource;
	}

	public void setOtherIncomeSource(Integer otherIncomeSource) {
		this.otherIncomeSource = otherIncomeSource;
	}

	@Column(name = "otherIncomeAmount")
	public Integer getOtherIncomeAmount() {
		return this.otherIncomeAmount;
	}

	public void setOtherIncomeAmount(Integer otherIncomeAmount) {
		this.otherIncomeAmount = otherIncomeAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
