package org.openhmis.domain;

// Generated Aug 5, 2015 8:35:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpMedicalAssistance generated by hbm2java
 */
@Entity
@Table(name = "TMP_MEDICAL_ASSISTANCE")
public class TmpMedicalAssistance implements java.io.Serializable {

	private Integer medicalAssistanceId;
	private Integer enrollmentId;
	private Date informationDate;
	private Integer hivAidsAssistance;
	private Integer noHivAidsAssistanceReason;
	private Integer adap;
	private Integer noAdapReason;

	public TmpMedicalAssistance() {
	}

	public TmpMedicalAssistance(Integer enrollmentId, Date informationDate,
			Integer hivAidsAssistance, Integer noHivAidsAssistanceReason,
			Integer adap, Integer noAdapReason) {
		this.enrollmentId = enrollmentId;
		this.informationDate = informationDate;
		this.hivAidsAssistance = hivAidsAssistance;
		this.noHivAidsAssistanceReason = noHivAidsAssistanceReason;
		this.adap = adap;
		this.noAdapReason = noAdapReason;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "medicalAssistanceId", unique = true, nullable = false)
	public Integer getMedicalAssistanceId() {
		return this.medicalAssistanceId;
	}

	public void setMedicalAssistanceId(Integer medicalAssistanceId) {
		this.medicalAssistanceId = medicalAssistanceId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "informationDate", length = 10)
	public Date getInformationDate() {
		return this.informationDate;
	}

	public void setInformationDate(Date informationDate) {
		this.informationDate = informationDate;
	}

	@Column(name = "hivAidsAssistance")
	public Integer getHivAidsAssistance() {
		return this.hivAidsAssistance;
	}

	public void setHivAidsAssistance(Integer hivAidsAssistance) {
		this.hivAidsAssistance = hivAidsAssistance;
	}

	@Column(name = "noHivAidsAssistanceReason")
	public Integer getNoHivAidsAssistanceReason() {
		return this.noHivAidsAssistanceReason;
	}

	public void setNoHivAidsAssistanceReason(Integer noHivAidsAssistanceReason) {
		this.noHivAidsAssistanceReason = noHivAidsAssistanceReason;
	}

	@Column(name = "adap")
	public Integer getAdap() {
		return this.adap;
	}

	public void setAdap(Integer adap) {
		this.adap = adap;
	}

	@Column(name = "noAdapReason")
	public Integer getNoAdapReason() {
		return this.noAdapReason;
	}

	public void setNoAdapReason(Integer noAdapReason) {
		this.noAdapReason = noAdapReason;
	}

}
