package org.openhmis.domain;

// Generated Aug 5, 2015 8:35:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpNonCashBenefit generated by hbm2java
 */
@Entity
@Table(name = "TMP_NON_CASH_BENEFIT")
public class TmpNonCashBenefit implements java.io.Serializable {

	private Integer nonCashBenefitId;
	private Integer enrollmentId;
	private Date informationDate;
	private Integer benefitsFromAnySource;
	private Integer snap;
	private Integer wic;
	private Integer tanfChildCare;
	private Integer tanfTransportation;
	private Integer otherTanf;
	private Integer rentalAssistanceOngoing;
	private Integer otherBenefitsSource;
	private Integer rentalAssistanceTemp;
	private String otherBenefitsSourceIdentify;

	public TmpNonCashBenefit() {
	}

	public TmpNonCashBenefit(Integer enrollmentId, Date informationDate,
			Integer benefitsFromAnySource, Integer snap, Integer wic,
			Integer tanfChildCare, Integer tanfTransportation,
			Integer otherTanf, Integer rentalAssistanceOngoing,
			Integer otherBenefitsSource, Integer rentalAssistanceTemp,
			String otherBenefitsSourceIdentify) {
		this.enrollmentId = enrollmentId;
		this.informationDate = informationDate;
		this.benefitsFromAnySource = benefitsFromAnySource;
		this.snap = snap;
		this.wic = wic;
		this.tanfChildCare = tanfChildCare;
		this.tanfTransportation = tanfTransportation;
		this.otherTanf = otherTanf;
		this.rentalAssistanceOngoing = rentalAssistanceOngoing;
		this.otherBenefitsSource = otherBenefitsSource;
		this.rentalAssistanceTemp = rentalAssistanceTemp;
		this.otherBenefitsSourceIdentify = otherBenefitsSourceIdentify;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nonCashBenefitId", unique = true, nullable = false)
	public Integer getNonCashBenefitId() {
		return this.nonCashBenefitId;
	}

	public void setNonCashBenefitId(Integer nonCashBenefitId) {
		this.nonCashBenefitId = nonCashBenefitId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "informationDate", length = 10)
	public Date getInformationDate() {
		return this.informationDate;
	}

	public void setInformationDate(Date informationDate) {
		this.informationDate = informationDate;
	}

	@Column(name = "benefitsFromAnySource")
	public Integer getBenefitsFromAnySource() {
		return this.benefitsFromAnySource;
	}

	public void setBenefitsFromAnySource(Integer benefitsFromAnySource) {
		this.benefitsFromAnySource = benefitsFromAnySource;
	}

	@Column(name = "snap")
	public Integer getSnap() {
		return this.snap;
	}

	public void setSnap(Integer snap) {
		this.snap = snap;
	}

	@Column(name = "wic")
	public Integer getWic() {
		return this.wic;
	}

	public void setWic(Integer wic) {
		this.wic = wic;
	}

	@Column(name = "tanfChildCare")
	public Integer getTanfChildCare() {
		return this.tanfChildCare;
	}

	public void setTanfChildCare(Integer tanfChildCare) {
		this.tanfChildCare = tanfChildCare;
	}

	@Column(name = "tanfTransportation")
	public Integer getTanfTransportation() {
		return this.tanfTransportation;
	}

	public void setTanfTransportation(Integer tanfTransportation) {
		this.tanfTransportation = tanfTransportation;
	}

	@Column(name = "otherTanf")
	public Integer getOtherTanf() {
		return this.otherTanf;
	}

	public void setOtherTanf(Integer otherTanf) {
		this.otherTanf = otherTanf;
	}

	@Column(name = "rentalAssistanceOngoing")
	public Integer getRentalAssistanceOngoing() {
		return this.rentalAssistanceOngoing;
	}

	public void setRentalAssistanceOngoing(Integer rentalAssistanceOngoing) {
		this.rentalAssistanceOngoing = rentalAssistanceOngoing;
	}

	@Column(name = "otherBenefitsSource")
	public Integer getOtherBenefitsSource() {
		return this.otherBenefitsSource;
	}

	public void setOtherBenefitsSource(Integer otherBenefitsSource) {
		this.otherBenefitsSource = otherBenefitsSource;
	}

	@Column(name = "rentalAssistanceTemp")
	public Integer getRentalAssistanceTemp() {
		return this.rentalAssistanceTemp;
	}

	public void setRentalAssistanceTemp(Integer rentalAssistanceTemp) {
		this.rentalAssistanceTemp = rentalAssistanceTemp;
	}

	@Column(name = "otherBenefitsSourceIdentify")
	public String getOtherBenefitsSourceIdentify() {
		return this.otherBenefitsSourceIdentify;
	}

	public void setOtherBenefitsSourceIdentify(
			String otherBenefitsSourceIdentify) {
		this.otherBenefitsSourceIdentify = otherBenefitsSourceIdentify;
	}

}
