package org.openhmis.domain;

// Generated Aug 4, 2015 1:51:42 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpProjectSite generated by hbm2java
 */
@Entity
@Table(name = "TMP_PROJECT_SITE")
public class TmpProjectSite implements java.io.Serializable {

	private Integer siteId;
	private Integer projectCoCId;
	private Integer principalSite;
	private String geocode;
	private String address;
	private String city;
	private String state;
	private String zip;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpProjectSite() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "siteId", unique = true, nullable = false)
	public Integer getSiteId() {
		return this.siteId;
	}

	public void setSiteId(Integer siteId) {
		this.siteId = siteId;
	}

	@Column(name = "projectCoCId")
	public Integer getProjectCoCId() {
		return this.projectCoCId;
	}

	public void setProjectCoCId(Integer projectCoCId) {
		this.projectCoCId = projectCoCId;
	}

	@Column(name = "principalSite")
	public Integer getPrincipalSite() {
		return this.principalSite;
	}

	public void setPrincipalSite(Integer principalSite) {
		this.principalSite = principalSite;
	}

	@Column(name = "geocode")
	public String getGeocode() {
		return this.geocode;
	}

	public void setGeocode(String geocode) {
		this.geocode = geocode;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip")
	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
