package org.openhmis.domain;



// Generated Aug 5, 2015 10:00:15 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpReferral generated by hbm2java
 */
@Entity
@Table(name = "TMP_REFERRAL")
public class TmpReferral implements java.io.Serializable {

	private Integer referralId;
	private Integer enrollmentId;
	private Date referralDate;
	private Integer pathTypeProvided;
	private Integer referralOutcome;
	private Integer rhyTypeProvided;
	private Date dateCreated;
	private Date dateUpdated;

	public TmpReferral() {
	}

	public TmpReferral(Integer enrollmentId, Date referralDate,
			Integer pathTypeProvided, Integer referralOutcome,
			Integer rhyTypeProvided, Date dateCreated, Date dateUpdated) {
		this.enrollmentId = enrollmentId;
		this.referralDate = referralDate;
		this.pathTypeProvided = pathTypeProvided;
		this.referralOutcome = referralOutcome;
		this.rhyTypeProvided = rhyTypeProvided;
		this.dateCreated = dateCreated;
		this.dateUpdated = dateUpdated;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "referralId", unique = true, nullable = false)
	public Integer getReferralId() {
		return this.referralId;
	}

	public void setReferralId(Integer referralId) {
		this.referralId = referralId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "referralDate", length = 10)
	public Date getReferralDate() {
		return this.referralDate;
	}

	public void setReferralDate(Date referralDate) {
		this.referralDate = referralDate;
	}

	@Column(name = "pathTypeProvided")
	public Integer getPathTypeProvided() {
		return this.pathTypeProvided;
	}

	public void setPathTypeProvided(Integer pathTypeProvided) {
		this.pathTypeProvided = pathTypeProvided;
	}

	@Column(name = "referralOutcome")
	public Integer getReferralOutcome() {
		return this.referralOutcome;
	}

	public void setReferralOutcome(Integer referralOutcome) {
		this.referralOutcome = referralOutcome;
	}

	@Column(name = "rhyTypeProvided")
	public Integer getRhyTypeProvided() {
		return this.rhyTypeProvided;
	}

	public void setRhyTypeProvided(Integer rhyTypeProvided) {
		this.rhyTypeProvided = rhyTypeProvided;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateCreated", length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateUpdated", length = 10)
	public Date getDateUpdated() {
		return this.dateUpdated;
	}

	public void setDateUpdated(Date dateUpdated) {
		this.dateUpdated = dateUpdated;
	}

}
