package org.openhmis.domain;

// Generated Aug 5, 2015 8:35:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmpService generated by hbm2java
 */
@Entity
@Table(name = "TMP_SERVICE")
public class TmpService implements java.io.Serializable {

	private Integer serviceId;
	private Integer enrollmentId;
	private Date dateProvided;
	private Integer pathTypeProvided;
	private Integer rhyTypeProvided;
	private Integer hopwaTypeProvided;
	private Integer ssvfTypeProvided;
	private Integer ssvfVaSubTypeProvided;
	private Integer ssvfCoordinatingSubTypeProvided;
	private Integer ssvfDirectSubTypeProvided;
	private String ssvfOtherService;

	public TmpService() {
	}

	public TmpService(Integer enrollmentId, Date dateProvided,
			Integer pathTypeProvided, Integer rhyTypeProvided,
			Integer hopwaTypeProvided, Integer ssvfTypeProvided,
			Integer ssvfVaSubTypeProvided,
			Integer ssvfCoordinatingSubTypeProvided,
			Integer ssvfDirectSubTypeProvided, String ssvfOtherService) {
		this.enrollmentId = enrollmentId;
		this.dateProvided = dateProvided;
		this.pathTypeProvided = pathTypeProvided;
		this.rhyTypeProvided = rhyTypeProvided;
		this.hopwaTypeProvided = hopwaTypeProvided;
		this.ssvfTypeProvided = ssvfTypeProvided;
		this.ssvfVaSubTypeProvided = ssvfVaSubTypeProvided;
		this.ssvfCoordinatingSubTypeProvided = ssvfCoordinatingSubTypeProvided;
		this.ssvfDirectSubTypeProvided = ssvfDirectSubTypeProvided;
		this.ssvfOtherService = ssvfOtherService;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "serviceId", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@Column(name = "enrollmentId")
	public Integer getEnrollmentId() {
		return this.enrollmentId;
	}

	public void setEnrollmentId(Integer enrollmentId) {
		this.enrollmentId = enrollmentId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateProvided", length = 10)
	public Date getDateProvided() {
		return this.dateProvided;
	}

	public void setDateProvided(Date dateProvided) {
		this.dateProvided = dateProvided;
	}

	@Column(name = "pathTypeProvided")
	public Integer getPathTypeProvided() {
		return this.pathTypeProvided;
	}

	public void setPathTypeProvided(Integer pathTypeProvided) {
		this.pathTypeProvided = pathTypeProvided;
	}

	@Column(name = "rhyTypeProvided")
	public Integer getRhyTypeProvided() {
		return this.rhyTypeProvided;
	}

	public void setRhyTypeProvided(Integer rhyTypeProvided) {
		this.rhyTypeProvided = rhyTypeProvided;
	}

	@Column(name = "hopwaTypeProvided")
	public Integer getHopwaTypeProvided() {
		return this.hopwaTypeProvided;
	}

	public void setHopwaTypeProvided(Integer hopwaTypeProvided) {
		this.hopwaTypeProvided = hopwaTypeProvided;
	}

	@Column(name = "ssvfTypeProvided")
	public Integer getSsvfTypeProvided() {
		return this.ssvfTypeProvided;
	}

	public void setSsvfTypeProvided(Integer ssvfTypeProvided) {
		this.ssvfTypeProvided = ssvfTypeProvided;
	}

	@Column(name = "ssvfVaSubTypeProvided")
	public Integer getSsvfVaSubTypeProvided() {
		return this.ssvfVaSubTypeProvided;
	}

	public void setSsvfVaSubTypeProvided(Integer ssvfVaSubTypeProvided) {
		this.ssvfVaSubTypeProvided = ssvfVaSubTypeProvided;
	}

	@Column(name = "ssvfCoordinatingSubTypeProvided")
	public Integer getSsvfCoordinatingSubTypeProvided() {
		return this.ssvfCoordinatingSubTypeProvided;
	}

	public void setSsvfCoordinatingSubTypeProvided(
			Integer ssvfCoordinatingSubTypeProvided) {
		this.ssvfCoordinatingSubTypeProvided = ssvfCoordinatingSubTypeProvided;
	}

	@Column(name = "ssvfDirectSubTypeProvided")
	public Integer getSsvfDirectSubTypeProvided() {
		return this.ssvfDirectSubTypeProvided;
	}

	public void setSsvfDirectSubTypeProvided(Integer ssvfDirectSubTypeProvided) {
		this.ssvfDirectSubTypeProvided = ssvfDirectSubTypeProvided;
	}

	@Column(name = "ssvfOtherService")
	public String getSsvfOtherService() {
		return this.ssvfOtherService;
	}

	public void setSsvfOtherService(String ssvfOtherService) {
		this.ssvfOtherService = ssvfOtherService;
	}

}
