--------------------------------------------------------
--  DDL for Table PATH_CLIENT_VETERAN_INFO
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_VETERAN_INFO" 
   (	"VETERAN_KEY" NUMBER, 
	"CLIENT_KEY" NUMBER, 
	"YR_ENTER_MILITARY" VARCHAR2(20), 
	"YR_SEP_MILITARY" VARCHAR2(20), 
	"MILITARY_BRANCH" NUMBER, 
	"DISCHARGE_STATUS" NUMBER, 
	"WORLD_WAR_II" NUMBER, 
	"KOREAN_WAR" NUMBER, 
	"VIETNAM_WAR" NUMBER, 
	"PERSIAN_WAR" NUMBER, 
	"AFGHANISTAN_WAR" NUMBER, 
	"IRAQ_FREEDOM" NUMBER, 
	"IRAQ_DAWN" NUMBER, 
	"OTHER" NUMBER, 
	"CREATE_USER_KEY" VARCHAR2(20), 
	"UPDATE_USER_KEY" VARCHAR2(20), 
	"CREATE_DATE" DATE, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"VERIFIED_DATE" DATE
   ) ;
