--------------------------------------------------------
--  DDL for Table PATH_CLIENT_INCOME_CASH
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_INCOME_CASH" 
   (	"INCOME_KEY" NUMBER(*,0), 
	"CLIENT_KEY" NUMBER(38,0), 
	"INCOME_CATEGORY_KEY" NUMBER(*,0), 
	"CREATE_DATE" DATE, 
	"CREATE_USER_KEY" NUMBER(*,0), 
	"MONTHLY_AMOUNT" NUMBER(10,2), 
	"START_DATE" DATE, 
	"ENDING_DATE" DATE, 
	"ACTIVE" CHAR(1), 
	"INCOME_GROUP_KEY" NUMBER(*,0), 
	"INCOME_ANSWER" NUMBER, 
	"VERIFIED_DATE" DATE, 
	"VERIFIED_ANSWER" NUMBER, 
	"DESCRIPTION" VARCHAR2(100), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2)
   ) ;
