--------------------------------------------------------
--  DDL for Table PATH_CLIENT_CHRONIC_HOMELESS
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_CHRONIC_HOMELESS" 
   (	"CREATE_USER_KEY" NUMBER, 
	"CREATE_DATE" DATE DEFAULT sysdate, 
	"UPDATE_USER_KEY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"CLIENT_KEY" NUMBER, 
	"AGENCY_KEY" NUMBER, 
	"HOMELESS" CHAR(1), 
	"CHRONICALLY_HOMELESS" CHAR(1), 
	"ZIPCODE_LAST_PERM_ADDRESS" VARCHAR2(5), 
	"PRIOR_NIGHTS_RESIDENCE_KEY" NUMBER, 
	"LENGTH_OF_STAY_KEY" NUMBER, 
	"ENTRY_DATE" DATE, 
	"ZIP_QUALITY_CODE" NUMBER, 
	"PRIOR_RESIDENCE_OTHER" VARCHAR2(50), 
	"HOMELESS_STATUS_KEY" NUMBER, 
	"CLIENT_PROGRAM_KEY" NUMBER, 
	"COLLECT_STAGE" NUMBER, 
	"DISABLING_CONDITION" NUMBER, 
	"PRIMARY_KEY" NUMBER(*,0), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2), 
	"CONTINUOUSLY_HL_ONEYEAR" VARCHAR2(20), 
	"TIMES_HL_PAST_THREEYEARS" NUMBER, 
	"MONTHS_HL_PAST_THREEYEARS" NUMBER, 
	"YEARS_HL_CONTINUOUSLY" NUMBER, 
	"STATUS_DOCUMENTED" VARCHAR2(100), 
	"MOVE_IN_PERM_HOUSING" CHAR(1), 
	"PERM_MOVE_IN_DATE" DATE, 
	"PROGRAM_RELATIONSHIP_KEY" NUMBER, 
	"CLIENT_LOCATION" NUMBER, 
	"CLIENT_ASSESSMENT_ID" NUMBER, 
	"CLIENT_ASSESSMENT_AGE" NUMBER, 
	"ASSESS_TYPE" NUMBER
   ) ;
