--------------------------------------------------------
--  DDL for Table PATH_CLIENT_AGENCY_INFO
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_AGENCY_INFO" 
   (	"CLIENT_KEY" NUMBER(*,0), 
	"AGENCY_KEY" NUMBER(*,0), 
	"PERMISSION_ON_FILE" CHAR(1), 
	"CREATE_USER_KEY" NUMBER(*,0), 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"REVOKE_USER_KEY" NUMBER(*,0), 
	"REVOKE_DATE" DATE, 
	"AUTH_GRANTED_DATE" DATE, 
	"AUTH_USER_KEY" NUMBER, 
	"AUTH_EXPIRATION_DATE" DATE, 
	"PRIMARY_KEYWORD_KEY" NUMBER, 
	"AGENCY_KEYWORDS" VARCHAR2(4000), 
	"PRIMARY_KEY" NUMBER(*,0), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2)
   ) ;
