--------------------------------------------------------
--  DDL for Table PATH_CLIENT_PROGRAM
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_PROGRAM" 
   (	"PROGRAM_KEY" NUMBER, 
	"CLIENT_KEY" NUMBER, 
	"ENTRY_DATE" DATE, 
	"ENTRY_CASH_GK" NUMBER, 
	"ENTRY_NONCASH_GK" NUMBER, 
	"EXIT_DATE" DATE, 
	"EXIT_CASH_GK" NUMBER, 
	"EXIT_NONCASH_GK" NUMBER, 
	"PROGRAM_NAME_KEY" NUMBER, 
	"DESTINATION_KEY" NUMBER, 
	"REASON_LEAVING_KEY" NUMBER, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"CREATE_USER_KEY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_KEY" NUMBER, 
	"STATUS" CHAR(1) DEFAULT 'A', 
	"TENURE_KEY" NUMBER(1,0) DEFAULT 8, 
	"SUBSIDY_KEY" NUMBER(1,0), 
	"REC_ACTIVE" CHAR(1) DEFAULT 'A', 
	"SUBSIDY_OTHERS" VARCHAR2(50), 
	"REASON_LEAVING_OTHERS" VARCHAR2(50), 
	"DESTINATION_OTHERS" VARCHAR2(50), 
	"HOUSING_STATUS_KEY" NUMBER, 
	"COUNTYNAME" VARCHAR2(64), 
	"ENGAGEMENT_DATE" DATE, 
	"BARCODE_PROFILE_KEY" NUMBER(*,0), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2), 
	"ANNUAL_CASH_GK" NUMBER, 
	"ANNUAL_NONCASH_GK" NUMBER
   ) ;
 

   COMMENT ON COLUMN "PATH_CLIENT_PROGRAM"."ENTRY_CASH_GK" IS 'Group Key from PATH_CLIENT_INCOME_CASH for Entry';
 
   COMMENT ON COLUMN "PATH_CLIENT_PROGRAM"."ENTRY_NONCASH_GK" IS 'Group Key from PATH_CLIENT_INCOME_NONCASH';
