--------------------------------------------------------
--  DDL for Table PATH_CLIENT_INCOME_NONCASH
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_INCOME_NONCASH" 
   (	"INCOME_KEY" NUMBER(*,0), 
	"CLIENT_KEY" NUMBER(38,0), 
	"INCOME_CATEGORY_KEY" NUMBER(*,0), 
	"START_DATE" DATE, 
	"ENDING_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_KEY" NUMBER(*,0), 
	"ACTIVE" CHAR(1), 
	"NON_CASH_GROUP_KEY" NUMBER(*,0), 
	"NON_CASH_ANSWER" NUMBER, 
	"VERIFIED_DATE" DATE, 
	"VERIFIED_ANSWER" NUMBER, 
	"DESCRIPTION" VARCHAR2(200), 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2), 
	"HEALTH_INSURANCE_GROUP_KEY" NUMBER(*,0)
   ) ;
