--------------------------------------------------------
--  DDL for Table PATH_CLIENT_STATUS
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_STATUS" 
   (	"CLIENT_STATUS_KEY" NUMBER, 
	"STATUS_KEY" NUMBER, 
	"CURRENT_STATUS_KEY" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_KEY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_KEY" NUMBER, 
	"REC_ACTIVE" CHAR(1), 
	"DESCRIPTION" VARCHAR2(200), 
	"CLIENT_KEY" NUMBER, 
	"UPDATE_AGENCY_KEY" NUMBER, 
	"ENTERED_DATE" DATE, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2)
   ) ;
