--------------------------------------------------------
--  DDL for Table PATH_CODE_HUD_PROGRAM
--------------------------------------------------------

  CREATE TABLE "PATH_CODE_HUD_PROGRAM" 
   (	"PROGRAM_KEY" NUMBER, 
	"PROGRAM_DESCRIPTION" VARCHAR2(35), 
	"AGENCY_KEY" NUMBER, 
	"STATUS" CHAR(1) DEFAULT 'A', 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"LENGTH_IN_DAYS" NUMBER, 
	"BED_PROGRAM" CHAR(1) DEFAULT 'N', 
	"TARGET_POPULATION" VARCHAR2(50), 
	"PROGRAM_TYPE_KEY" NUMBER, 
	"FIPS_CODE" NUMBER, 
	"FACILITY_CODE" VARCHAR2(10), 
	"COC_CODE" VARCHAR2(5), 
	"INDIVIDUAL_FAMILY_CODE" NUMBER, 
	"PROGRAM_PARENT_ID" VARCHAR2(32), 
	"PROGRAM_TYPE_CODE_OTHER" VARCHAR2(50), 
	"SITE_KEY" NUMBER, 
	"PROGRAM_DES_DETAIL" VARCHAR2(200), 
	"HPRP" CHAR(1), 
	"HMIS_RESIDENTIAL_UTILIZATION" NUMBER, 
	"TARGET_POPULATION_A" NUMBER, 
	"TARGET_POPULATION_B" NUMBER, 
	"MULTI_COUNTY" CHAR(1), 
	"COC_KEY" NUMBER, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"READ_PROGRAM" CHAR(1), 
	"EMPTY_BEDS" NUMBER, 
	"MIGRATION_FLAG" CHAR(2), 
	"PATH" CHAR(1), 
	"HOPWA" CHAR(1), 
	"RHY" CHAR(1), 
	"IS_CONTINUUM" CHAR(1), 
	"AFFILIATED" NUMBER, 
	"IS_SHARED" CHAR(1), 
	"BED_TRACKING" NUMBER DEFAULT 0
   ) ;
 

   COMMENT ON COLUMN "PATH_CODE_HUD_PROGRAM"."PROGRAM_DESCRIPTION" IS 'Displays as Program Name in interface';
 
   COMMENT ON COLUMN "PATH_CODE_HUD_PROGRAM"."PROGRAM_DES_DETAIL" IS 'Displays as Description in interface';
 
   COMMENT ON COLUMN "PATH_CODE_HUD_PROGRAM"."COC_KEY" IS 'Relates record to PATH_COMMUNITY ';
