REM INSERTING into PATH_CODE_THEATRE_OPERATIONS
SET DEFINE OFF;
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','World War II',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','Korean War',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Vietnam War',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Persian Gulf War (Oper. Desert Storm)',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Afghanistan (Oper. Enduring Freedom)',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Iraq (Oper. Iraqi Freedom)',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','Iraq (Oper. New Dawn)',null,null);
Insert into PATH_CODE_THEATRE_OPERATIONS (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Other Peace-keeping Ops or Military Interventions (Lebanon, Panama, Bosnia, Somalia, Kosovo)',null,null);
