REM INSERTING into PATH_CODE_ID_TYPE
SET DEFINE OFF;
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (1,'A','Full SSN',null,null,2);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (9,'A','Client Refused',null,null,7);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (0,'A','(Select)',null,null,1);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (2,'A','Approximate or Partial SSN',null,null,3);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (3,'I','Other',null,null,4);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (4,'I','State',null,null,5);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (8,'A','Client Doesn''t Know / Have',null,null,6);
Insert into PATH_CODE_ID_TYPE (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG,SORT_ORDER) values (99,'A','Data Not Collected',null,null,8);
