REM INSERTING into PATH_CODE_MILITARY_ERA
SET DEFINE OFF;
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Persian Gulf Era (August 1991 - September 10, 2001)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','Post Vietnam (May 1975 - July 1991)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Vietnam Era (August 1964 - April 1975)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Between Korean and Vietnam War (February 1955 - July 1964)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Korean War (June 1950 - January 1955)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Between WWII and Korean War (August 1947 - May 1950)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','World War II (September 1940 - July 1947)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Don''t Know',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Refused',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,'I','Between WWI and WWII (December 1918 - August 1940)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,'I','World War I (April 1917 - November 1918)',null,null);
Insert into PATH_CODE_MILITARY_ERA (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'A','Post September 11, 2001 (September 11, 2001 - Present)',null,null);
