REM INSERTING into PATH_CODE_REASON_FOR_LEAVING
SET DEFINE OFF;
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'I','Voluntary departure',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,'A','Non-payment of rent/occupancy charge',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (14,'A','Non-compliance with program',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (15,'A','Unknown/disappeared',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (16,'A','Criminal activity/destruction of property/violence',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (17,'A','Death',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (18,'I','Ineligible for service',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (0,'A','(None)',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (19,'A','Left for a housing opportunity before completing program',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (20,'A','Completed program',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (22,'A','Reached maximum time allowed in program',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (23,'A','Needs could not be met by program',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (24,'A','Disagreement with rules/persons',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (25,'A','Other',null,null);
Insert into PATH_CODE_REASON_FOR_LEAVING (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'I','Left for a housing opportunity before completing program',null,null);
