REM INSERTING into PATH_CODE_SPECIAL_NEEDS
SET DEFINE OFF;
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'Homeless','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,'At risk of Homelessness','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'Chronically Homeless (HUD Definition)','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'Severely Mentally Ill','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'Substance Abuse (Alcohol &/or Drugs)','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'HIV: Persons with HIV/AIDS','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'Other Disability','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'VET: Veterans','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'DV: Domestic Violence victims','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'Elderly (ages 62 and older)','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,'Illiterate or Marginally Literate','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,'Criminal History','A',null,null);
Insert into PATH_CODE_SPECIAL_NEEDS (CODE_KEY,CODE_NAME,STATUS,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'NA: Not Applicable','A',null,null);
