REM INSERTING into PATH_CODE_DESTINATION
SET DEFINE OFF;
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Emergency shelter, including hotel or motel paid for with E.S.voucher',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (2,'A','Transitional housing for homeless persons (including homeless youth)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (3,'A','Permanent supportive housing for formerly homeless persons',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (4,'A','Psychiatric hospital or other psychiatric facility',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (5,'A','Substance abuse treatment facility or detox center',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (6,'A','Hospital or other residential non-psychiatric medical facility',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (7,'A','Jail, prison or juvenile detention facility',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (10,'A','Rental by client, no ongoing housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (11,'A','Owned by client, no ongoing housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (12,'A','Staying or living with family, temporary tenure (e.g., room, apartment or house)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (13,'A','Staying or living with friends, temporary tenure (e.g., room, apartment or house)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (14,'A','Hotel or motel paid for without emergency shelter voucher',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (15,'A','Foster care home or foster care group home',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (16,'A','Place not meant for habitation',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (17,'A','Other',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Client Doesn''t Know',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Client Refused',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (106,'I','Psychiatric hospital',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (107,'I','Inpatient alcohol or other drug treatment facility',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (109,'I','Jail/prison',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (110,'I','Places not meant for human habitation (e.g. street)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (111,'I','Emergency shelter',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (112,'I','Unknown',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (0,'A','(None)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (113,'I','Rental house or apartment (no subsidy)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (114,'I','Public Housing',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (115,'I','Section 8',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (116,'I','Shelter Plus Care',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (117,'I','HOME subsidized house or apartment',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (118,'I','Other subsidized house or apartment',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (119,'I','Homeownership',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (120,'I','Moved in with family or friends-Permanent',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (121,'I','Transitional housing for homeless persons',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (122,'I','Moved in with family or friends-Transitional',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (123,'I','Other supportive housing',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (124,'I','Other',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (24,'A','Deceased',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (23,'A','Staying or living with friends, permanent tenure',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (22,'A','Staying or living with family, permanent tenure',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (21,'A','Owned by client, with housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (20,'A','Rental by client, with other ongoing housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (19,'A','Rental by client, with VASH housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (18,'A','Safe Haven',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (805,'I','HOPWA program',to_timestamp('10-OCT-13 10.37.08.000000000 AM','DD-MON-RR HH.MI.SSXFF AM'),null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (806,'I','Staying or living with family, temporary tenure (e.g., room, apartment or house)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (807,'I','Staying or living with friends, temporary tenure (e.g., room, apartment or house)',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (25,'A','Long-term care facility or nursing home',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (26,'A','Moved from one HOPWA funded project to HOPWA PH',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (27,'A','Moved from one HOPWA funded project to HOPWA TH',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (28,'A','Rental by client, with GPD TIP housing subsidy',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (29,'A','Residential project or halfway house with no homeless criteria',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data Not Collected',null,null);
Insert into PATH_CODE_DESTINATION (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (30,'A','No exit interview completed',null,null);
