REM INSERTING into PATH_CODE_GENERAL
SET DEFINE OFF;
Insert into PATH_CODE_GENERAL (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (0,'A','No',null,null);
Insert into PATH_CODE_GENERAL (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (1,'A','Yes',null,null);
Insert into PATH_CODE_GENERAL (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (8,'A','Client Doesn''t Know',null,null);
Insert into PATH_CODE_GENERAL (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (9,'A','Client Refused',null,null);
Insert into PATH_CODE_GENERAL (CODE_KEY,STATUS,DESCRIPTION,UPDATE_TIMESTAMP,MIGRATION_FLAG) values (99,'A','Data Not Collected',null,null);
