--------------------------------------------------------
--  DDL for Table PATH_HOUSEHOLD_CLIENT
--------------------------------------------------------

  CREATE TABLE "PATH_HOUSEHOLD_CLIENT" 
   (	"HOUSEHOLD_CLIENT_KEY" NUMBER, 
	"HOUSEHOLD_KEY" NUMBER, 
	"CLIENT_KEY" NUMBER, 
	"STATUS" CHAR(10), 
	"RELATIONSHIP_KEY" NUMBER, 
	"DATE_LEFT" DATE, 
	"DATE_ENTERED" DATE, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_KEY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_KEY" NUMBER, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2)
   ) ;
