--------------------------------------------------------
--  DDL for Table PATH_CLIENT_HEALTH_INSURANCE
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_HEALTH_INSURANCE" 
   (	"CLIENT_KEY" NUMBER(*,0), 
	"GROUP_KEY" NUMBER(*,0), 
	"COLLECT_STAGE" NUMBER(*,0), 
	"PROG_ENROLL_KEY" NUMBER(*,0), 
	"INFO_DATE" DATE, 
	"COVERED" CHAR(1), 
	"MEDECAID" CHAR(1), 
	"MEDICARE" CHAR(1), 
	"STATE_CHIP" CHAR(1), 
	"VA_MED_SERVICES" CHAR(1), 
	"EMPLOYER" CHAR(1), 
	"COBRA" CHAR(1), 
	"PRIVATE" CHAR(1), 
	"STATE_ADULTS" CHAR(1), 
	"REASON_CODE" NUMBER, 
	"CREATE_DATE" DATE, 
	"CREATE_USER_KEY" NUMBER(*,0), 
	"UPDATE_DATE" DATE, 
	"UPDATE_USER_KEY" NUMBER(*,0), 
	"NONCASH_GROUP_KEY" NUMBER, 
	"VERIFIED_DATE" DATE, 
	"VERIFIED_ANSWER" NUMBER, 
	"MEDECAID_DATE" DATE, 
	"MEDICARE_DATE" DATE, 
	"STATE_CHIP_DATE" DATE, 
	"VA_MED_SERVICES_DATE" DATE, 
	"EMPLOYER_DATE" DATE, 
	"COBRA_DATE" DATE, 
	"PRIVATE_DATE" DATE, 
	"STATE_ADULTS_DATE" DATE
   ) ;
