--------------------------------------------------------
--  DDL for Table PATH_CLIENT_SPECIAL_NEEDS
--------------------------------------------------------

  CREATE TABLE "PATH_CLIENT_SPECIAL_NEEDS" 
   (	"NEEDS_KEY" NUMBER, 
	"CLIENT_KEY" NUMBER, 
	"AGENCY_KEY" NUMBER, 
	"NEEDS_CODE_KEY" NUMBER, 
	"ANSWER_KEY" NUMBER, 
	"SECONDARY_QUESTION_CODE_1" NUMBER, 
	"SECONDARY_QUESTION_CODE_2" NUMBER, 
	"RESPONSE_CODE" NUMBER, 
	"CREATE_USER_KEY" NUMBER, 
	"CREATE_DATE" DATE DEFAULT SYSDATE, 
	"UPDATE_USER_KEY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"GROUP_KEY" NUMBER, 
	"UPDATE_TIMESTAMP" TIMESTAMP (6), 
	"MIGRATION_FLAG" CHAR(2), 
	"SECONDARY_QUESTION_CODE_4" NUMBER, 
	"SECONDARY_QUESTION_CODE_5" NUMBER, 
	"SECONDARY_QUESTION_CODE_3" NUMBER, 
	"VERIFIED_DATE" DATE
   ) ;
