CREATE TABLE `TMP_EXIT` (
	exitId INT AUTO_INCREMENT PRIMARY KEY,
	enrollmentId INT,
	projectExitDate DATE,
	destinationTypeCode INT,
	otherDestination VARCHAR(255),
	assessmentDisposition INT,
	otherDisposition VARCHAR(255),
	housingAssessment INT,
	subsidyInformation INT,
	connectionWithSoar INT,
	employedInformationDate DATE,
	employed INT,
	employmentType INT,
	notEmployedReason INT,
	generalHealthStatus INT,
	dentalHealthStatus INT,
	mentalHealthStatus INT,
	writtenAftercarePlan INT,
	assistanceMainstreamBenefits INT,
	permanentHousingPlacement INT,
	temporaryShelterPlacement INT,
	exitCounciling INT,
	furtherFollowupServices INT,
	scheduledFollowupContacts INT,
	resourcePackage INT,
	otherAftercarePlanOrAction INT,
	projectCompletionStatus INT,
	earlyExitReason INT,
	earlyExpulsionReason INT,
	familyReunificationCode INT
);