CREATE TABLE `AGENCY` (
  `AGENCY_KEY` bigint(20) NOT NULL AUTO_INCREMENT,
  `AGENCY_NAME` varchar(300) DEFAULT NULL,
  `DIRECT_SERVICE_GCT` int(11) DEFAULT NULL,
  `REC_ACTIVE_GCT` int(11) DEFAULT '1',
  `ENTRY_DATE_TIME` timestamp NULL DEFAULT NULL,
  `ENTRY_USER_KEY` bigint(20) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  `AGENCY_DISPLAY_NAME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`AGENCY_KEY`),
  KEY `AGENCY_DSG` (`DIRECT_SERVICE_GCT`)
) ENGINE=InnoDB AUTO_INCREMENT=14265 DEFAULT CHARSET=utf8;