CREATE TABLE `CODE_HEALTH_STATUS` (
  `CODE_KEY` int(11) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `SHORT_DESCRIPTION` varchar(200) DEFAULT NULL,
  `REC_ACTIVE` int(11) DEFAULT NULL,
  `NOTES` varchar(400) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`CODE_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;