CREATE TABLE `GROUP_INFO` (
  `GROUP_KEY` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(200) DEFAULT NULL,
  `TYPE_CODE` int(11) DEFAULT NULL,
  `DESCRIPTION` varchar(400) DEFAULT NULL,
  `CITY` varchar(40) DEFAULT NULL,
  `COUNTY` varchar(40) DEFAULT NULL,
  `STATE_CODE` int(11) DEFAULT NULL,
  `HUD_COC_ID` varchar(40) DEFAULT NULL,
  `HUD_COC_NAME` varchar(120) DEFAULT NULL,
  `REC_ACTIVE_GCT` int(11) DEFAULT '1',
  `ENTRY_DATE_TIME` timestamp NULL DEFAULT NULL,
  `ENTRY_USER_KEY` bigint(20) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`GROUP_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;