CREATE TABLE `SERVICE_EVENT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_KEY` bigint(20) DEFAULT NULL,
  `TAXONOMY_CODE` bigint(20) DEFAULT NULL,
  `SERVICE_DATE` date DEFAULT NULL,
  `OUTCOME_CODE` int(11) DEFAULT NULL,
  `NOTE` varchar(4000) DEFAULT NULL,
  `REC_ACTIVE_GCT` int(11) DEFAULT '1',
  `ENTRY_DATE_TIME` timestamp NULL DEFAULT NULL,
  `ENTRY_USER_KEY` bigint(20) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;