CREATE TABLE `USER_INFO` (
  `USER_KEY` bigint(20) NOT NULL AUTO_INCREMENT,
  `AGENCY_KEY` bigint(20) DEFAULT NULL,
  `USER_ID` varchar(200) DEFAULT NULL,
  `PASSWORD_ENC` varchar(200) DEFAULT NULL,
  `PW_EXPIRE_DATE` date DEFAULT NULL,
  `NAME_FIRST` varchar(200) DEFAULT NULL,
  `NAME_LAST` varchar(200) DEFAULT NULL,
  `USER_ACTIVE_GCT` int(11) DEFAULT '1',
  `REC_ACTIVE_GCT` int(11) DEFAULT '1',
  `ENTRY_DATE_TIME` timestamp NULL DEFAULT NULL,
  `ENTRY_USER_KEY` bigint(20) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`USER_KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;