CREATE TABLE `CLIENT_RACE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CLIENT_KEY` bigint(20) NOT NULL,
  `RACE_CODE` int(11) NOT NULL,
  `REC_ACTIVE_GCT` int(11) DEFAULT NULL,
  `ENTRY_DATE_TIME` timestamp NULL DEFAULT NULL,
  `ENTRY_USER_KEY` bigint(20) DEFAULT NULL,
  `LOG_DATE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LOG_USER_KEY` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CR_CK_IDX` (`CLIENT_KEY`),
  KEY `CR_RACE_CODE_IDX` (`RACE_CODE`),
  KEY `CR_REC_ACTIVE_GCT_IDX` (`REC_ACTIVE_GCT`),
  CONSTRAINT `FK_CLIENT_RACE` FOREIGN KEY (`RACE_CODE`) REFERENCES `CODE_RACE` (`CODE_KEY`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;